apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: database-migration
          image: busybox
          command: [ "sh", "-c" ]
          args:
            - "echo 'Running database migrations...'; sleep 30; echo 'Migration completed successfully!'"
      restartPolicy: Never
