apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    spec:
      containers:
        - name: database-migration
          image: busybox
          command: [ "sh", "-c" ]
          args:
            - "echo 'Running database migrations...'; sleep 30; echo 'Migration completed successfully!'"
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host
      restartPolicy: Never
